import {
  AirVent,
  AlarmSmoke,
  Bath,
  BookOpen,
  BriefcaseMedical,
  Building2,
  Car,
  Cctv,
  Circle,
  Coffee,
  CookingPot,
  Dice5,
  Droplet,
  Dumbbell,
  Fence,
  FireExtinguisher,
  Flame,
  FlameKindling,
  KeyRound,
  Laptop,
  Mountain,
  Sailboat,
  Ship,
  Speaker,
  Trees,
  Tv,
  Umbrella,
  WashingMachine,
  WavesLadder,
  Wifi,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  wifi: Wifi,
  "cooking-pot": CookingPot,
  "air-vent": AirVent,
  flame: Flame,
  tv: Tv,
  "washing-machine": WashingMachine,
  laptop: Laptop,
  droplet: Droplet,
  waves: WavesLadder,
  car: Car,
  bath: Bath,
  "flame-kindling": FlameKindling,
  fireplace: Flame,
  dumbbell: Dumbbell,
  "dice-5": Dice5,
  "book-open": BookOpen,
  speaker: Speaker,
  fence: Fence,
  coffee: Coffee,
  "key-round": KeyRound,
  umbrella: Umbrella,
  sailboat: Sailboat,
  mountain: Mountain,
  trees: Trees,
  "building-2": Building2,
  ship: Ship,
  "alarm-smoke": AlarmSmoke,
  "fire-extinguisher": FireExtinguisher,
  "briefcase-medical": BriefcaseMedical,
  cctv: Cctv,
};

export function amenityIcon(name: string): LucideIcon {
  return ICONS[name] ?? Circle;
}
